# Generated by Django 4.1.3 on 2022-11-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=20)),
                ('sub_model', models.CharField(max_length=20)),
            ],
        ),
    ]
