# Generated by Django 4.1.3 on 2022-11-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_airplane_sub_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='number',
            new_name='code',
        ),
    ]
