# Generated by Django 4.1.3 on 2022-11-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_number_airplane_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='manufacturer',
            field=models.CharField(max_length=20),
        ),
    ]
