# Generated by Django 4.1.3 on 2022-11-28 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_airplane_code_alter_airplane_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('pilot_rating', models.CharField(max_length=20, null=True)),
                ('job', models.CharField(choices=[('HOST', 'HOST'), ('PILOT', 'PILOT'), ('STAFF', 'STAFF')], default='STAFF', max_length=6)),
                ('airplane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.airplane')),
            ],
        ),
    ]
