# Generated by Django 4.1.3 on 2022-11-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passport_no', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=6)),
                ('place_of_birth', models.CharField(max_length=20)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
            ],
        ),
    ]
