# Generated by Django 4.1.3 on 2022-11-28 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('flight_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('airplane', models.IntegerField()),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('ARRIVE', 'ARRIVE'), ('DEPARTURE', 'DEPARTURE'), ('IDLE', 'IDLE'), ('CANCEL', 'CANCEL')], default='IDLE', max_length=10)),
                ('airport_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='app.airport')),
                ('airport_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='app.airport')),
            ],
        ),
    ]
