# Generated by Django 4.1.3 on 2022-11-28 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_flightschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.airplane'),
        ),
    ]
