# Generated by Django 4.1.3 on 2022-11-28 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_flightschedule_airplane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightschedule',
            old_name='flight_schedule_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='airplane',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pilot_rating',
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pilot_rating', models.CharField(max_length=20, null=True)),
                ('job', models.CharField(choices=[('HOST', 'HOST'), ('PILOT', 'PILOT'), ('STAFF', 'STAFF')], default='STAFF', max_length=6)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.airplane')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
