# Generated by Django 4.1.3 on 2022-11-28 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_flight_schedule_id_flightschedule_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASSIGN', 'ASSIGN'), ('CANCEL', 'CANCEL')], default='ASSIGN', max_length=10)),
                ('employee_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employeecontract')),
                ('flight_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flightschedule')),
            ],
        ),
    ]
