# Generated by Django 4.1.3 on 2022-11-28 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
                ('flight_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flightschedule')),
            ],
        ),
    ]
