# Generated by Django 4.1.3 on 2022-11-28 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_connect', models.BooleanField()),
                ('flight_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flightschedule')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.passenger')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.price')),
            ],
        ),
    ]
